<?php include '_salutation.phtml' ?>
Please click on the following link to to confirm your login from <?php echo $this->country ?>.<br />
<br />
<a href="<?php echo $this->url('country', array('action' => 'country-confirm', 'code' => $this->code, 'country' => $this->countryCode), array('force_canonical' => true)); ?>"><?php echo $this->url('country', array('action' => 'country-confirm', 'code' => $this->code, 'country' => $this->countryCode), array('force_canonical' => true)); ?></a>